### ISSUE TITLE
Not working in Win 11 ?

### ISSUE THREAD

**Issue by olluz** [costasf-glitch/OutlookMessageSearch#2] opened 2023-10-29 21:16 UTC
The installation package could not be opened. Contact the application vendor to verify this is a valid Windows Installer package.

**Comment by costasf-glitch** [comment] 2023-10-29 22:43
That's odd.  I can't replicate on a new Windows 11 install.  Make sure that the contents of the zip file are unzipped before running the installer.

The installation files haven't been touch since they were published about a year and a half ago.

You might get Windows SmartScreen warning in which case you would probably want to follow the [steps here](https://www.pcworld.com/article/406832/how-to-get-past-windows-defender-smartscreen-in-windows-10.html).

There may be a different Windows issue that need to be resolved regarding the Windows installation service.  In which case, follow the steps [here](https://www.thewindowsclub.com/this-installation-package-could-not-be-opened).

**Comment by costasf-glitch** [comment] 2023-11-11 16:36
Closing this as I can't reproduce.

**Closed as completed** 2023-11-11 16:36 UTC
